-- Your SQL goes here
CREATE TABLE work_unit(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  url VARCHAR NOT NULL UNIQUE,
  status VARCHAR NOT NULL DEFAULT 'pending',
  retry_count INTEGER NOT NULL DEFAULT 0,
  last_error VARCHAR,
  created_at VARCHAR NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE page(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  title VARCHAR NOT NULL,
  url VARCHAR NOT NULL UNIQUE,
  links VARCHAR NOT NULL,
  emails VARCHAR NOT NULL,
  coins VARCHAR NOT NULL,
  created_at VARCHAR NOT NULL DEFAULT CURRENT_TIMESTAMP
);
