-- Your SQL goes here
CREATE TABLE work_unit(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  url VARCHAR NOT NULL,
  processed BOOLEAN NOT NULL DEFAULT 0
);
CREATE TABLE page(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  title VARCHAR NOT NULL,
  url VARCHAR NOT NULL,
  links VARCHAR NOT NULL,
  emails VARCHAR NOT NULL,
  coins VARCHAR NOT NULL
);
