-- Your SQL goes here
CREATE TABLE WorkUnit(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  url VARCHAR NOT NULL
);
CREATE TABLE Page(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  title VARCHAR NOT NULL,
  url VARCHAR NOT NULL,
  links VARCHAR NOT NULL,
  emails VARCHAR NOT NULL,
  coins VARCHAR NOT NULL
);
