CREATE TABLE host_service_observation(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  host TEXT NOT NULL,
  service TEXT NOT NULL,
  port INTEGER NOT NULL,
  status TEXT NOT NULL,
  banner TEXT,
  banner_fingerprint TEXT,
  last_error TEXT,
  last_attempt_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  last_success_at TEXT,
  created_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(host, service, port)
);

CREATE INDEX idx_host_service_observation_service ON host_service_observation(service);
CREATE INDEX idx_host_service_observation_banner_fingerprint ON host_service_observation(service, banner_fingerprint);
