CREATE TABLE host_http_observation(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  host TEXT NOT NULL,
  scheme TEXT NOT NULL,
  port INTEGER NOT NULL,
  status TEXT NOT NULL,
  http_status_code INTEGER,
  final_url TEXT,
  server_header TEXT,
  powered_by_header TEXT,
  content_type_header TEXT,
  location_header TEXT,
  via_header TEXT,
  alt_svc_header TEXT,
  www_authenticate_header TEXT,
  set_cookie_names TEXT,
  response_headers TEXT,
  header_fingerprint TEXT,
  favicon_url TEXT,
  favicon_hash TEXT,
  last_error TEXT,
  last_attempt_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  last_success_at TEXT,
  created_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(host, scheme, port)
);

CREATE INDEX idx_host_http_observation_header_fingerprint ON host_http_observation(header_fingerprint);
CREATE INDEX idx_host_http_observation_favicon_hash ON host_http_observation(favicon_hash);

CREATE TABLE host_tls_observation(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  host TEXT NOT NULL,
  port INTEGER NOT NULL,
  status TEXT NOT NULL,
  certificate_sha256 TEXT,
  last_error TEXT,
  last_attempt_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  last_success_at TEXT,
  created_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(host, port)
);

CREATE INDEX idx_host_tls_observation_certificate_sha256 ON host_tls_observation(certificate_sha256);
