CREATE TABLE intel_lead(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_id TEXT NOT NULL,
  lead_key TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  summary TEXT NOT NULL,
  severity TEXT NOT NULL,
  confidence INTEGER NOT NULL DEFAULT 0,
  score INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'new',
  primary_entity_type TEXT NOT NULL DEFAULT '',
  primary_entity_value TEXT NOT NULL DEFAULT '',
  related_entity_type TEXT,
  related_entity_value TEXT,
  first_seen_at TEXT NOT NULL,
  last_seen_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  CHECK (score >= 0 AND score <= 100),
  CHECK (confidence >= 0 AND confidence <= 100),
  CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  CHECK (status IN ('new', 'triaged', 'monitoring', 'suppressed'))
);

CREATE INDEX idx_intel_lead_status_severity_last_seen
  ON intel_lead(status, severity, last_seen_at DESC, id DESC);

CREATE INDEX idx_intel_lead_rule_last_seen
  ON intel_lead(rule_id, last_seen_at DESC, id DESC);

CREATE INDEX idx_intel_lead_score_last_seen
  ON intel_lead(score DESC, last_seen_at DESC, id DESC);

CREATE INDEX idx_intel_lead_primary_entity
  ON intel_lead(primary_entity_type, primary_entity_value);

CREATE TABLE intel_lead_evidence(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id INTEGER NOT NULL REFERENCES intel_lead(id) ON DELETE CASCADE,
  source_type TEXT NOT NULL,
  source_id INTEGER NOT NULL DEFAULT 0,
  source_key TEXT NOT NULL DEFAULT '',
  evidence_text TEXT NOT NULL,
  observed_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(lead_id, source_type, source_id, source_key, evidence_text)
);

CREATE INDEX idx_intel_lead_evidence_lead_observed
  ON intel_lead_evidence(lead_id, observed_at DESC, id DESC);

CREATE INDEX idx_intel_lead_evidence_source
  ON intel_lead_evidence(source_type, source_id, source_key);
