CREATE TABLE auto_blacklist_rule(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_type TEXT NOT NULL,
  value TEXT NOT NULL,
  label TEXT NOT NULL DEFAULT '',
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  CHECK (rule_type IN ('site_category', 'keyword')),
  CHECK (value <> '')
);

CREATE UNIQUE INDEX idx_auto_blacklist_rule_type_value
  ON auto_blacklist_rule(rule_type, lower(value));

CREATE INDEX idx_auto_blacklist_rule_enabled_type
  ON auto_blacklist_rule(enabled, rule_type, id);

CREATE TABLE auto_blacklist_event(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_id INTEGER NOT NULL REFERENCES auto_blacklist_rule(id) ON DELETE CASCADE,
  domain TEXT NOT NULL,
  source_page_id INTEGER REFERENCES page(id) ON DELETE SET NULL,
  rule_type TEXT NOT NULL,
  matched_value TEXT NOT NULL,
  evidence TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  CHECK (domain <> ''),
  CHECK (rule_type IN ('site_category', 'keyword')),
  CHECK (matched_value <> '')
);

CREATE UNIQUE INDEX idx_auto_blacklist_event_unique_page
  ON auto_blacklist_event(domain, rule_id, COALESCE(source_page_id, 0));

CREATE INDEX idx_auto_blacklist_event_domain
  ON auto_blacklist_event(domain, created_at DESC);

CREATE INDEX idx_auto_blacklist_event_created_at
  ON auto_blacklist_event(created_at DESC, id DESC);
