CREATE TABLE watchlist_item(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_type TEXT NOT NULL,
  value TEXT NOT NULL,
  label TEXT NOT NULL DEFAULT '',
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  CHECK (item_type IN (
    'domain',
    'url',
    'email',
    'crypto',
    'keyword',
    'ssh_fingerprint',
    'http_fingerprint',
    'favicon_hash'
  )),
  CHECK (value <> '')
);

CREATE UNIQUE INDEX idx_watchlist_item_type_value
  ON watchlist_item(item_type, lower(value));

CREATE INDEX idx_watchlist_item_enabled_type
  ON watchlist_item(enabled, item_type, id);
