CREATE TABLE work_unit(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'pending',
  retry_count INTEGER NOT NULL DEFAULT 0,
  next_attempt_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  last_attempt_at TEXT,
  last_error TEXT,
  created_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX idx_work_unit_status_next_attempt_at ON work_unit(status, next_attempt_at);

CREATE TABLE page(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  url TEXT NOT NULL UNIQUE,
  links TEXT NOT NULL DEFAULT '',
  emails TEXT NOT NULL DEFAULT '',
  coins TEXT NOT NULL DEFAULT '',
  language TEXT NOT NULL DEFAULT '',
  last_scanned_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  created_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE page_scan(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id INTEGER NOT NULL REFERENCES page(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  language TEXT NOT NULL DEFAULT '',
  scanned_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX idx_page_scan_page_id_scanned_at ON page_scan(page_id, scanned_at DESC);

CREATE TABLE page_scan_link(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scan_id INTEGER NOT NULL REFERENCES page_scan(id) ON DELETE CASCADE,
  target_url TEXT NOT NULL,
  target_host TEXT NOT NULL DEFAULT '',
  UNIQUE(scan_id, target_url)
);

CREATE INDEX idx_page_scan_link_target_host ON page_scan_link(target_host);

CREATE TABLE page_scan_email(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scan_id INTEGER NOT NULL REFERENCES page_scan(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  UNIQUE(scan_id, email)
);

CREATE INDEX idx_page_scan_email_email ON page_scan_email(email);

CREATE TABLE page_scan_crypto(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scan_id INTEGER NOT NULL REFERENCES page_scan(id) ON DELETE CASCADE,
  asset_type TEXT NOT NULL,
  reference TEXT NOT NULL,
  UNIQUE(scan_id, asset_type, reference)
);

CREATE INDEX idx_page_scan_crypto_lookup ON page_scan_crypto(asset_type, reference);

CREATE TABLE page_link(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_page_id INTEGER NOT NULL REFERENCES page(id) ON DELETE CASCADE,
  target_url TEXT NOT NULL,
  target_host TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(source_page_id, target_url)
);

CREATE INDEX idx_page_link_target_host ON page_link(target_host);

CREATE TABLE page_email(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id INTEGER NOT NULL REFERENCES page(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(page_id, email)
);

CREATE INDEX idx_page_email_email ON page_email(email);

CREATE TABLE page_crypto(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id INTEGER NOT NULL REFERENCES page(id) ON DELETE CASCADE,
  asset_type TEXT NOT NULL,
  reference TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(page_id, asset_type, reference)
);

CREATE INDEX idx_page_crypto_lookup ON page_crypto(asset_type, reference);

CREATE TABLE page_classification(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id INTEGER NOT NULL UNIQUE REFERENCES page(id) ON DELETE CASCADE,
  host TEXT NOT NULL,
  category TEXT NOT NULL,
  confidence TEXT NOT NULL,
  score INTEGER NOT NULL DEFAULT 0,
  evidence TEXT NOT NULL DEFAULT '',
  last_classified_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX idx_page_classification_host ON page_classification(host);

CREATE TABLE site_profile(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  host TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL,
  confidence TEXT NOT NULL,
  score INTEGER NOT NULL DEFAULT 0,
  page_count INTEGER NOT NULL DEFAULT 0,
  evidence TEXT NOT NULL DEFAULT '',
  source_page_id INTEGER REFERENCES page(id) ON DELETE SET NULL,
  last_classified_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  created_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE domain_blacklist(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  domain TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE host_ssh_observation(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  host TEXT NOT NULL,
  port INTEGER NOT NULL,
  status TEXT NOT NULL,
  host_key_algorithm TEXT,
  host_key TEXT,
  host_key_fingerprint TEXT,
  server_banner TEXT,
  last_error TEXT,
  last_attempt_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  last_success_at TEXT,
  created_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(host, port)
);

CREATE INDEX idx_host_ssh_observation_fingerprint ON host_ssh_observation(host_key_algorithm, host_key_fingerprint);

CREATE TABLE forum_keyword_rule(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label TEXT NOT NULL,
  pattern TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(label, pattern)
);

CREATE INDEX idx_forum_keyword_rule_label ON forum_keyword_rule(label);

CREATE TABLE page_keyword_tag(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id INTEGER NOT NULL REFERENCES page(id) ON DELETE CASCADE,
  tag TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(page_id, tag)
);

CREATE INDEX idx_page_keyword_tag_page_id ON page_keyword_tag(page_id);
CREATE INDEX idx_page_keyword_tag_tag ON page_keyword_tag(tag);
