CREATE TABLE page_language_detection(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id INTEGER NOT NULL REFERENCES page(id) ON DELETE CASCADE,
  language_code TEXT NOT NULL DEFAULT '',
  language_name TEXT NOT NULL DEFAULT 'Unknown',
  confidence INTEGER NOT NULL DEFAULT 0,
  source TEXT NOT NULL DEFAULT '',
  evidence TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(page_id),
  CHECK (confidence >= 0 AND confidence <= 100)
);

CREATE INDEX idx_page_language_detection_language
  ON page_language_detection(language_code, confidence DESC);

CREATE TABLE page_topic_tag(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id INTEGER NOT NULL REFERENCES page(id) ON DELETE CASCADE,
  topic TEXT NOT NULL,
  score INTEGER NOT NULL DEFAULT 0,
  confidence TEXT NOT NULL DEFAULT 'low',
  evidence TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(page_id, topic),
  CHECK (score >= 0 AND score <= 100),
  CHECK (confidence IN ('low', 'medium', 'high'))
);

CREATE INDEX idx_page_topic_tag_topic_score
  ON page_topic_tag(topic, score DESC, page_id);
